apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.service_name }}'
  labels:
    app: '{{ .Values.general.deployment_name }}'
spec:
  type: NodePort
  ports:
  - name: server
    protocol: TCP
    port: {{ .Values.configs.networking.server }}
    targetPort: {{ .Values.configs.networking.server }}
    nodePort: {{ .Values.configs.networking.server }}
  - name: rest
    protocol: TCP
    appProtocol: http
    port: {{ .Values.configs.networking.rest }}
    targetPort: {{ .Values.configs.networking.rest }}
    nodePort: {{ .Values.configs.networking.rest }}
  {{- if ne .Values.configs.networking.broker "" }}
  - name: broker
    protocol: TCP
    port: {{ .Values.configs.networking.broker }}
    targetPort: {{ .Values.configs.networking.broker }}
    nodePort: {{ .Values.configs.networking.broker }}
  {{ end }}
  selector:
    app: '{{ .Values.general.app_name }}'
