# Based on: https://github.com/DrSnowbird/mongo-compass-docker/blob/master/docker-compose.yml
# Mongo Express URL: http://${YOUR_URL}:28081/

version: '3.3'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      #MONGODB_AUTH_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - type: volume 
        source: mongo-data 
        target: /data/db 
      - type: volume
        source: mongo-configs
        target: /data/configdb

#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    restart: always
#    ports:
#      - "28081:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
#      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
#      ME_CONFIG_MONGODB_URL: mongo://${MONGO_USER}:${MONGO_USER}@mongo:27017/
#    depends_on:
#      - mongo
volumes:
  mongo-data:
    driver: local
  mongo-configs:
    driver: local