apiVersion: apps/v1
kind: Deployment
metadata:
  name: anylog-master
  labels:
    app: anylog-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anylog-master
  template:
    metadata:
      labels:
        app: anylog-master
    spec:
      imagePullSecrets:
      - name: imagepullsecret
      containers:
      - name: anylog-master
        image: anylogco/anylog-network:predevelop
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: master-configurations
        ports:
          - containerPort: 32048
            name: master-tcp
          - containerPort: 32049
            name: master-rest