apiVersion: v1
kind: ConfigMap
metadata:
  name: master-node-configuration
  labels:
    app: anylog-master
data:
  NODE_TYPE: "master"
  NODE_NAME: "master-node"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32048"
  ANYLOG_REST_PORT: "32049"
  MASTER_NODE: "100.115.6.114:32048"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  MQTT_ENABLE: "false"
  DEPLOY_LOCAL_SCRIPT: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: anylog-master
  labels:
    app: anylog-master
spec:
  type: NodePort
  ports:
  - name: anylog-master-tcp
    protocol: TCP
    port: 32048
    targetPort: 32048
    nodePort: 32048
  - name: anylog-master-rest
    protocol: TCP
    port: 32049
    targetPort: 32049
    nodePort: 32049
  selector:
    app: anylog-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-master
  labels:
    app: anylog-master
spec:
  serviceName: "anylog-master"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-master
  template:
    metadata:
      labels:
        app: anylog-master
    spec:
      imagePullSecrets:
      - name: imagepullsecret
      containers:
      - name: anylog-master
        image: nvcr.io/uazwwnrnci5h/anylog/anylog-network:demo
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: master-node-configuration
        ports:
          - containerPort: 32048
            name: tcp
          - containerPort: 32049
            name: rest
