apiVersion: apps/v1
kind: Deployment
metadata:
  name: al-nvidia-operator1
  labels:
    app: al-nvidia-operator1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: al-nvidia-operator1
  template:
    metadata:
      labels:
        app: al-nvidia-operator1
    spec:
      imagePullSecrets:
      - name: imagepullsecret
      containers:
      - name: al-nvidia-operator1
        image: nvcr.io/uazwwnrnci5h/anylog/anylog-network:demo
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: operator1-configurations
        env:
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: operator1-secret-configurations
                key: DB_PASSWD
        ports:
          - containerPort: 32148
            name: tcp
          - containerPort: 32149
            name: rest