apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configuration
  labels:
    app: anylog-query
data:
  NODE_TYPE: "query"
  NODE_NAME: "query-node"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32348"
  ANYLOG_REST_PORT: "32349"
  MASTER_NODE: "anylog-master:32048"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  MQTT_ENABLE: "false"
  DEPLOY_LOCAL_SCRIPT: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: anylog-query
  labels:
    app: anylog-query
spec:
  ports:
  - port: 32348
    name: anylog-query-tcp
  - port: 32349
    name: anylog-query-rest
  selector:
    app: anylog-query
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-query
  labels:
    app: anylog-query
spec:
  serviceName: "anylog-query"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-query
  template:
    metadata:
      labels:
        app: anylog-query
    spec:
      imagePullSecrets:
      - name: anylogregistrykey
      containers:
      - name: anylog-query
        image: anylogco/anylog-network:develop
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: node-configuration
        ports:
          - containerPort: 32348
            name: tcp
          - containerPort: 32349
            name: rest