apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_USER: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-configs
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: ZGVtbwo= # demo | base64