apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql-0
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv-postgresql-0/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql-1
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv-postgresql-1/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql-2
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv-postgresql-2/
---
