kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.generic.volume_name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.volume.storageClass }}
  capacity:
    storage: {{ .Values.volume.capacity }}
  accessModes:
    - {{ .Values.volume.accessMode }}
  hostPath:
    path: {{ .Values.volume.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.generic.volume_claim_name }}
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  storageClassName: {{ .Values.volume.storageClass }}
  accessModes:
  - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}
