apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.deployment_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.general.app_name }}'
  template:
    metadata:
      name: '{{ .Values.general.deployment_name }}'
      labels:
        app: {{ .Values.general.app_name }}
    spec:
      containers:
      - name: '{{ .Values.general.deployment_name }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        envFrom:
          - configMapRef:
              name: '{{ .Values.general.configmap_name }}'
        ports:
        - name: '{{ .Values.networking.port_name }}'
          containerPort: 3000

        volumeMounts:
          {{- if eq .Values.general.enable_volume true }}
          - mountPath: '/var/lib/grafana'
            name: {{ .Values.general.volume_name }}-data
          - mountPath: '/var/log/grafana'
            name: {{ .Values.general.volume_name }}-logs
          - mountPath: '/etc/grafana'
            name: { { .Values.general.volume_name } }-config
         {{ end }}

      volumes:
        {{- if eq .Values.general.enable_volume true }}
        - name: {{ .Values.general.volume_name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.general.volume_name }}-data-claim
        - name: {{ .Values.general.volume_name }}-logs
          persistentVolumeClaim:
            claimName: {{ .Values.general.volume_name }}-logs-claim
        - name: {{ .Values.general.volume_name }}-config
          persistentVolumeClaim:
            claimName: {{ .Values.general.volume_name }}-config-claim
        {{ end }}
