apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.deployment_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.general.app_name }}'
  template:
    metadata:
      name: '{{ .Values.general.deployment_name }}'
      labels:
        app: {{ .Values.general.app_name }}
    spec:
      containers:
      - name: '{{ .Values.general.deployment_name }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        envFrom:
          - configMapRef:
              name: '{{ .Values.general.configmap_name }}'
        ports:
        - name: '{{ .Values.networking.port_name }}'
          containerPort: 3000
        {{- if .Values.general.enable_volume true }}
        volumeMounts:
          - name: {{ .Values.general.volume_name }}
            mountPath: /var/lib/grafana/
        {{ end }}
      {{- if .Values.general.enable_volume true }}
      volumes:
        - name: {{ .Values.general.volume_name }}
          emptyDir: {}
          persistentVolumeClaim:
            claimName: {{ .Values.general.volume_name }}-claim
      {{ end }}