apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.service_name }}'
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  type: NodePort
  ports:
  - name: '{{ .Values.networking.port_name }}'
    protocol: TCP
    appProtocol: http
    port: 3000
    targetPort: 3000
    nodePort: 31000
