apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: grafana
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.networking.node_port }}
  selector:
    app: '{{ .Values.general.app_name }}'
