version: "3"
services:
  anylog-master:
    image: anylogco/anylog-network:${TAG}
    privileged: true
    restart: always
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "udp://$(ifconfig | grep 'inet ' | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1):514"
#        syslog-facility: "daemon"
#        syslog-format: "rfc5424"
    env_file:
      - anylog_configs.env
      - advance_configs.env
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    network_mode: host
#    ports:
#      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
#      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
    environment:
      - INIT_TYPE=${INIT_TYPE}
    volumes:
      - anylog-master-anylog:/app/AnyLog-Network/anylog
      - anylog-master-blockchain:/app/AnyLog-Network/blockchain
      - anylog-master-data:/app/AnyLog-Network/data
      - anylog-master-local-scripts:/app/deployment-scripts
      - anylog-master-syslog-volume:/var/log/syslog
      - ${NEBULA_CONFIG_FILE}:${ANYLOG_PATH}/nebula/config.yml
      - anylog-master-nebula-configs:${ANYLOG_PATH}/nebula/
volumes:
  anylog-master-anylog:
  anylog-master-blockchain:
  anylog-master-data:
  anylog-master-local-scripts:
  anylog-master-syslog-volume: