general:
  namespace: default
  app_name: grafana
  deployment_name: grafana-app
  service_name: grafana-svs
  configmap_name: grafana-configs
  replicas: 1
  volume_name: grafana-pv

spec:
  storage_class: manual
  access_mode: ReadWriteMany
  storage_size: 5Gi
  reclaim_policy: Retain
  host_path: /opt/grafana-data

image:
  repository: grafana/grafana
  tag: 7.5.7
  pullPolicy: Always

networking:
  port_name: grafana-port
  node_port: 31000

configs:
  username: admin
  password: admin
  disable_login_form: false
  enable_anonymous: true
  enable_embedding: true
  plugins: [
      simpod-json-datasource,
      grafana-worldmap-panel
  ]

