#-----------------------------------------------------------------------------------------------------------------------
# The following YAML file sets the configurations for AnyLog's Remote CLI
# GitHub Repo: https://github.com/AnyLog-co/remote-cli
#-----------------------------------------------------------------------------------------------------------------------
general:
  namespace: default
  app_name: remote-cli
  deployment_name: remote-cli-app
  service_name: remote-cli-svs
  configmap_name: remote-cli-configs
  replicas: 1

image:
  secretName: ""
  repository: anylogco/remote-cli
  tag: latest
  pullPolicy: IfNotPresent

networking:
  ip: 0.0.0.0
  port_name: rmt-cli-port
  # the port value should be 30000 - 32767 as the service is configured to NodePort port used for:
  # - port
  # - nodePort
  # - targetPort
  port: 31800
