apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.deployment_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  type: NodePort
  ports:
  - name: '{{ .Values.networking.port_name }}'
    protocol: TCP
    appProtocol: http
    port: {{ .Values.networking.port }}
    targetPort: {{ .Values.networking.port }}
    nodePort: {{ .Values.networking.port }}
  selector:
    app: '{{ .Values.general.app_name }}'
