apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.configmap_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
data:
  # -- Directories --
  ANYLOG_PATH: '{{ .Values.node_configs.directories.ANYLOG_PATH }}'
  LOCAL_SCRIPTS: '{{ .Values.node_configs.directories.LOCAL_SCRIPTS }}'
  TEST_DIR: '{{ .Values.node_configs.directories.TEST_DIR }}'
  
  # -- General --
  LICENSE_KEY: '{{ .Values.node_configs.general.LICENSE_KEY }}'
  NODE_TYPE: '{{ .Values.node_configs.general.NODE_TYPE }}'
  NODE_NAME: '{{ .Values.node_configs.general.NODE_NAME }}'
  COMPANY_NAME: '{{ .Values.node_configs.general.COMPANY_NAME }}'

  # -- Geolocation --
  {{ if ne .Values.node_configs.geolocation.LOCATION "" }}
  LOCATION: '{{ .Values.node_configs.geolocation.LOCATION }}'
  {{ end }}
  {{ if ne .Values.node_configs.geolocation.COUNTRY "" }}
  COUNTRY: '{{ .Values.node_configs.geolocation.COUNTRY }}'
  {{ end }}
  {{ if ne .Values.node_configs.geolocation.STATE "" }}
  STATE: '{{ .Values.node_configs.geolocation.STATE }}'
  {{ end }}
  {{ if ne .Values.node_configs.geolocation.CITY "" }}
  CITY: '{{ .Values.node_configs.geolocation.CITY }}'
  {{ end }}

  # -- Networking --
  ANYLOG_SERVER_PORT: '{{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}'
  ANYLOG_REST_PORT: '{{ .Values.node_configs.networking.ANYLOG_REST_PORT }}'

  {{ if ne .Values.node_configs.networking.CONFIG_NAME "" }}
  CONFIG_NAME: '{{ .Values.node_configs.networking.CONFIG_NAME }}'
  {{ end }}

  {{ if ne .Values.node_configs.networking.OVERLAY_IP "" }}
  OVERLAY_IP: '{{ .Values.node_configs.networking.OVERLAY_IP }}'
  {{ end }}

  {{ if ne .Values.node_configs.networking.PROXY_IP "" }}
  PROXY_IP: '{{ .Values.node_configs.networking.PROXY_IP }}'
  {{ end }}

  {{ if ne .Values.node_configs.networking.ANYLOG_BROKER_PORT "" }}
  ANYLOG_BROKER_PORT: '{{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}'
  {{ end }}

  TCP_BIND: '{{ .Values.node_configs.networking.TCP_BIND }}'
  TCP_THREADS: '{{ .Values.node_configs.networking.TCP_THREADS }}'
  REST_BIND: '{{ .Values.node_configs.networking.REST_BIND }}'
  REST_TIMEOUT: '{{ .Values.node_configs.networking.REST_TIMEOUT }}'
  REST_THREADS: '{{ .Values.node_configs.networking.REST_THREADS }}'
  BROKER_BIND: '{{ .Values.node_configs.networking.BROKER_BIND }}'
  BROKER_THREADS: '{{ .Values.node_configs.networking.BROKER_THREADS }}'

  # -- Database --
  # SQL database
  DB_TYPE: '{{ .Values.node_configs.database.DB_TYPE }}'

  {{ if ne .Values.node_configs.database.DB_USER "" }}
  DB_USER: '{{ .Values.node_configs.database.DB_USER }}'
  {{ end }}
  {{ if ne .Values.node_configs.database.DB_PASSWD "" }}
  DB_PASSWD: '{{ .Values.node_configs.database.DB_PASSWD }}'
  {{ end }}
  {{ if ne .Values.node_configs.database.DB_IP "" }}
  DB_IP: '{{ .Values.node_configs.database.DB_IP }}'
  {{ end }}
  {{ if ne .Values.node_configs.database.DB_PORT "" }}
  DB_PORT: '{{ .Values.node_configs.database.DB_PORT }}'
  {{ end }}

  AUTOCOMMIT: '{{ .Values.node_configs.database.AUTOCOMMIT }}'
  SYSTEM_QUERY: '{{ .Values.node_configs.database.SYSTEM_QUERY }}'
  MEMORY: '{{ .Values.node_configs.database.MEMORY }}'

  # NoSQL database
  ENABLE_NOSQL: '{{ .Values.node_configs.database.ENABLE_NOSQL }}'
  {{ if ne .Values.node_configs.database.NOSQL_USER "" }}
  NOSQL_USER: '{{ .Values.node_configs.database.NOSQL_USER }}'
  {{ end }}
  {{ if ne .Values.node_configs.database.NOSQL_PASSWD "" }}
  NOSQL_PASSWD: '{{ .Values.node_configs.database.NOSQL_PASSWD }}'
  {{ end }}
  NOSQL_IP: '{{ .Values.node_configs.database.NOSQL_IP }}'
  NOSQL_PORT: '{{ .Values.node_configs.database.NOSQL_PORT }}'

  BLOBS_DBMS: '{{ default false .Values.node_configs.database.BLOBS_DBMS }}'
  {{ if eq .Values.node_configs.database.ENABLE_NOSQL "true" }}
  BLOBS_REUSE: '{{ default true .Values.node_configs.database.BLOBS_REUSE }}'
  {{ end }}

  BLOBS_REUSE: '{{ .Values.node_configs.database.BLOBS_REUSE }}'

  # -- blockchain --
  LEDGER_CONN: '{{ .Values.node_configs.blockchain.LEDGER_CONN }}'
  SYNC_TIME: '{{ .Values.node_configs.blockchain.SYNC_TIME }}'
  BLOCKCHAIN_SOURCE: '{{ .Values.node_configs.blockchain.BLOCKCHAIN_SOURCE }}'
  BLOCKCHAIN_DESTINATION: '{{ .Values.node_configs.blockchain.BLOCKCHAIN_DESTINATION }}'

  # -- Operator --
  {{ if or (eq .Values.node_configs.general.NODE_TYPE "operator") (eq .Values.node_configs.general.NODE_TYPE "generic") }}
  CLUSTER_NAME: '{{ .Values.node_configs.operator.CLUSTER_NAME }}'
  DEFAULT_DBMS: '{{ .Values.node_configs.operator.DEFAULT_DBMS }}'

  {{ if ne .Values.node_configs.operator.MEMBER "" }}
  MEMBER: '{{ .Values.node_configs.operator.MEMBER }}'
  {{ end }}

  ENABLE_HA: '{{ .Values.node_configs.operator.ENABLE_HA }}'
  START_DATE: '{{ .Values.node_configs.operator.START_DATE }}'
  ENABLE_PARTITIONS: '{{ .Values.node_configs.operator.ENABLE_PARTITIONS }}'
  TABLE_NAME: '{{ .Values.node_configs.operator.TABLE_NAME }}'
  PARTITION_COLUMN: '{{ .Values.node_configs.operator.PARTITION_COLUMN }}'
  PARTITION_INTERVAL: '{{ .Values.node_configs.operator.PARTITION_INTERVAL }}'
  PARTITION_KEEP: '{{ .Values.node_configs.operator.PARTITION_KEEP }}'
  OPERATOR_THREADS: '{{ .Values.node_configs.operator.OPERATOR_THREADS }}'
  {{ end }}

  # -- MQTT --
  {{ if or (eq .Values.node_configs.general.NODE_TYPE "operator") (eq .Values.node_configs.general.NODE_TYPE "generic") (eq .Values.node_configs.general.NODE_TYPE "publisher") }}
  ENABLE_MQTT: '{{ .Values.node_configs.mqtt.ENABLE_MQTT }}'
  MQTT_LOG: '{{ .Values.node_configs.mqtt.MQTT_LOG }}'
  MQTT_BROKER: '{{ .Values.node_configs.mqtt.MQTT_BROKER }}'
  MQTT_PORT: '{{ .Values.node_configs.mqtt.MQTT_PORT }}'
  {{ if ne .Values.node_configs.mqtt.MQTT_USER "" }}
  MQTT_USER: '{{ .Values.node_configs.mqtt.MQTT_USER }}'
  {{ end }}
  {{ if ne .Values.node_configs.mqtt.MQTT_PASSWD "" }}
  MQTT_PASSWD: '{{ .Values.node_configs.mqtt.MQTT_PASSWD }}'
  {{ end }}
  MQTT_TOPIC: '{{ .Values.node_configs.mqtt.MQTT_TOPIC }}'
  MQTT_DBMS: '{{ .Values.node_configs.mqtt.MQTT_DBMS }}'
  MQTT_TABLE: '{{ .Values.node_configs.mqtt.MQTT_TABLE }}'
  MQTT_TIMESTAMP_COLUMN: '{{ .Values.node_configs.mqtt.MQTT_TIMESTAMP_COLUMN }}'
  MQTT_VALUE_COLUMN: '{{ .Values.node_configs.mqtt.MQTT_VALUE_COLUMN }}'
  MQTT_VALUE_COLUMN_TYPE: '{{ .Values.node_configs.mqtt.MQTT_VALUE_COLUMN_TYPE }}'
  {{ end }}

  # -- Monitoring --
  MONITOR_NODES: '{{ .Values.node_configs.monitoring.MONITOR_NODES }}'
  MONITOR_NODE: '{{ .Values.node_configs.monitoring.MONITOR_NODE }}'
  MONITOR_NODE_COMPANY: '{{ .Values.node_configs.monitoring.MONITOR_NODE_COMPANY }}'

  # -- Advanced --
  DEPLOY_LOCAL_SCRIPT: '{{ .Values.node_configs.advanced.DEPLOY_LOCAL_SCRIPT }}'
  COMPRESS_FILE: '{{ .Values.node_configs.advanced.COMPRESS_FILE }}'
  QUERY_POOL: '{{ .Values.node_configs.advanced.QUERY_POOL }}'
  WRITE_IMMEDIATE: '{{ .Values.node_configs.advanced.WRITE_IMMEDIATE }}'
  THRESHOLD_TIME: '{{ .Values.node_configs.advanced.THRESHOLD_TIME }}'
  THRESHOLD_VOLUME: '{{ .Values.node_configs.advanced.THRESHOLD_VOLUME }}'


