apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configuration
  labels:
    app: anylog-standalone
data:
  NODE_TYPE: "standalone"
  NODE_NAME: "aarana-standalone-node"
  COMPANY_NAME: "Aarna"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32048"
  ANYLOG_REST_PORT: "32049"
  ANYLOG_BROKER_PORT: "32050"
  MASTER_NODE: "anylog-standalone:32048"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  # NEW_CLUSTER -- cluster name
  NEW_CLUSTER: "demo-cluster1"
  TABLE_NAME: "*"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "14 days"
  PARTITION_KEEP: "6"
  ENABLE_DATA_MONITOR: "false"

  MQTT_ENABLE: "false"
  DEPLOY_LOCAL_SCRIPT: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: anylog-standalone
  labels:
    app: anylog-standalone
spec:
  ports:
  - port: 32048
    name: anylog-standalone-tcp
  - port: 32049
    name: anylog-standalone-rest
  - port: 32050
    name: anylog-standalone-broker
  selector:
    app: anylog-standalone
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-standalone
  labels:
    app: anylog-standalone
spec:
  serviceName: "anylog-standalone"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-standalone
  template:
    metadata:
      labels:
        app: anylog-standalone
    spec:
      imagePullSecrets:
      - name: anylogregistrykey
      containers:
      - name: anylog-standalone
        image: anylogco/anylog-network:develop
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: node-configuration
        ports:
          - containerPort: 32048
            name: tcp
          - containerPort: 32049
            name: rest
          - containerPort: 32050
            name: broker
