apiVersion: v1
kind: ConfigMap
metadata:
  name: operator2-configurations
  labels:
    app: al-nvidia-operator2
data:
  NODE_TYPE: "operator"
  NODE_NAME: "operator-node2"
  COMPANY_NAME: "Nvidia"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32158"
  ANYLOG_REST_PORT: "32159"
  MASTER_NODE: "al-nvidia-master:32048"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  # NEW_CLUSTER -- cluster name
  CLUSTER_NAME: "demo-cluster2"
  TABLE_NAME: "*"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "7 days"
  PARTITION_KEEP: "2"
  ENABLE_DATA_MONITOR: "false"

  MQTT_ENABLE: "true"
  BROKER: "driver.cloudmqtt.com"
  MQTT_PORT: "18785"
  MQTT_USER: "ibglowct"
  MQTT_PASSWORD: "MSY4e009J7ts"
  MQTT_LOG: "false"
  MQTT_TOPIC_NAME: "anylogedgex"
  MQTT_TOPIC_DBMS: "test"
  # original value was "bring [device]" (Random-Integer-Generator01). howerver, due to a PSQL table name limit size is 65 chars, it's manually changeds to: rand_int
  MQTT_TOPIC_TABLE: "rand_data"
  MQTT_COLUMN_TIMESTAMP: "now"
  MQTT_COLUMN_VALUE_TYPE: "float"
  MQTT_COLUMN_VALUE: "bring [readings][][value]"

  DEPLOY_LOCAL_SCRIPT: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: operator2-secret-configurations
  labels:
    app: al-nvidia-operator2
data:
  DB_PASSWD: ZGVtbwo= # passwd | base64