apiVersion: apps/v1
kind: Deployment
metadata:
  name: al-nvidia-operator2
  labels:
    app: al-nvidia-operator2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: al-nvidia-operator2
  template:
    metadata:
      labels:
        app: al-nvidia-operator2
    spec:
      imagePullSecrets:
      - name: imagepullsecret
      containers:
      - name: al-nvidia-operator2
        image: nvcr.io/uazwwnrnci5h/anylog/anylog-network:demo
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: operator2-configurations
        env:
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: operator2-secret-configurations
                key: DB_PASSWD
        ports:
          - containerPort: 32158
            name: tcp
          - containerPort: 32159
            name: rest