version: "2.2"
services:
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "${CLI_PORT}:${CLI_PORT}"
    environment:
      - CONN_IP=${CONN_IP}
      - CLI_PORT=${CLI_PORT}
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  anylog-query-node:
    image: anylogco/anylog-network:${BUILD}
    env_file:
      - ${ENV_FILE}
    container_name: ${CONTAINER_NAME}
    restart: always
    stdin_open: true
    tty: true
    network_mode: "${NETWORK}"
    volumes:
      - anylog-query-node-anylog:/app/AnyLog-Network/anylog
      - anylog-query-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-query-node-data:/app/AnyLog-Network/data
      - anylog-query-node-local-scripts:/app/AnyLog-Network/scripts
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  remote-cli:
  remote-cli-current:
  anylog-query-node-anylog:
  anylog-query-node-blockchain:
  anylog-query-node-data:
  anylog-query-node-local-scripts: