apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configuration
  labels:
    app: anylog-publisher
data:
  NODE_TYPE: "publisher"
  NODE_NAME: "publisher-node"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32248"
  ANYLOG_REST_PORT: "32249"
  ANYLOG_BROKER_PORT: "32250"
  MASTER_NODE: "anylog-master:32248"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  MQTT_ENABLE: "false"
  DEPLOY_LOCAL_SCRIPT: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: anylog-publisher
  labels:
    app: anylog-publisher
spec:
  ports:
  - port: 32248
    name: anylog-publisher-tcp
  - port: 32249
    name: anylog-publisher-rest
  - port: 32250
    name: anylog-publisher-broker
  selector:
    app: anylog-publisher
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-publisher
  labels:
    app: anylog-publisher
spec:
  serviceName: "anylog-publisher"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-publisher
  template:
    metadata:
      labels:
        app: anylog-publisher
    spec:
      imagePullSecrets:
      - name: anylogregistrykey
      containers:
      - name: anylog-publisher
        image: anylogco/anylog-network:develop
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: node-configuration
        ports:
          - containerPort: 32248
            name: tcp
          - containerPort: 32249
            name: rest
          - containerPort: 32250
            name: broker
