version: "2.2"
services:
  anylog-operator:
    image: anylogco/anylog-network:${TAG}
    privileged: true
    restart: always
    env_file:
      - anylog_configs.env
      - advance_configs.env
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    network_mode: host
#    ports:
#      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
#      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
#      - ${ANYLOG_BROKER_PORT}:${ANYLOG_BROKER_PORT}
    environment:
      - INIT_TYPE=${INIT_TYPE}
    volumes:
      - anylog-operator-anylog:/app/AnyLog-Network/anylog
      - anylog-operator-blockchain:/app/AnyLog-Network/blockchain
      - anylog-operator-data:/app/AnyLog-Network/data
      - anylog-operator-local-scripts:/app/deployment-scripts
      - ${NEBULA_CONFIG_FILE}:${ANYLOG_PATH}/nebula/config.yml
      - anylog-operator-nebula:${ANYLOG_PATH}/nebula/
volumes:
  anylog-operator-anylog:
  anylog-operator-blockchain:
  anylog-operator-data:
  anylog-operator-local-scripts:
  anylog-operator-nebula: