version: "2.2"
services:
  anylog-operator:
    image: anylogco/anylog-network:${BUILD}
    restart: always
    env_file:
      - anylog_configs.env
      - advance_configs.env
    environment:
      - INIT_TYPE: "${INIT_TYPE}"
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    ports:
      - "${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}"
      - "${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}"
      - "${ANYLOG_BROKER_PORT}:${ANYLOG_BROKER_PORT}"
    volumes:
      - anylog-operator-anylog:/app/AnyLog-Network/anylog
      - anylog-operator-blockchain:/app/AnyLog-Network/blockchain
      - anylog-operator-data:/app/AnyLog-Network/data
      - anylog-operator-local-scripts:/app/deployment-scripts
volumes:
  anylog-operator-anylog:
  anylog-operator-blockchain:
  anylog-operator-data:
  anylog-operator-local-scripts:
