apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configuration
  labels:
    app: anylog-operator
data:
  NODE_TYPE: "operator"
  NODE_NAME: "operator-node"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32148"
  ANYLOG_REST_PORT: "32149"
  ANYLOG_BROKER_PORT: "32150"
  MASTER_NODE: "anylog-master:32148"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  # NEW_CLUSTER -- cluster name
  NEW_CLUSTER: "demo-cluster"
  TABLE_NAME: "*"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "14 days"
  PARTITION_KEEP: "6"
  ENABLE_DATA_MONITOR: "false"

  MQTT_ENABLE: "false"
  DEPLOY_LOCAL_SCRIPT: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: anylog-operator
  labels:
    app: anylog-operator
spec:
  ports:
  - port: 32148
    name: anylog-operator-tcp
  - port: 32149
    name: anylog-operator-rest
  - port: 32150
    name: anylog-operator-broker
  selector:
    app: anylog-operator
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-operator
  labels:
    app: anylog-operator
spec:
  serviceName: "anylog-operator"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-operator
  template:
    metadata:
      labels:
        app: anylog-operator
    spec:
      imagePullSecrets:
      - name: anylogregistrykey
      containers:
      - name: anylog-operator
        image: anylogco/anylog-network:develop
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: node-configuration
        ports:
          - containerPort: 32148
            name: tcp
          - containerPort: 32149
            name: rest
          - containerPort: 32150
            name: broker
