#----------------------------------------------------------------------------------------------------------------------
# The following are the general values used to deploy an AnyLog instance of type: Master | AnyLog version: develop
#----------------------------------------------------------------------------------------------------------------------
general:
  namespace: default
  app_name: anylog
  pod_name: anylog-master-pod
  deployment_name: anylog-master-app
  service_name: anylog-master-svs
  configmap_name: anylog-master-configs
  # nodeSelector - Allows running Kubernetes remotely. If commented out, code will ignore it
  #nodeSelector: ""
  replicas: 1
  
image:
  secretName: imagepullsecret
  repository: anylogco/anylog-network
  tag: predevelop
  pullPolicy: Always

configs:
  basic:
    node_type: ledger
    node_name: anylog-master-node
    company_name: New Company
    # if location is not set, will use `https://ipinfo.io/json` to get coordinates
    location: ""
    country: ""
    state: ""
    city: ""

  networking:
    server: 32048
    rest: 32049
    # Optional broker port
    broker: ""
    # master node is not needed for REST node
    # Optional external & local IP instead of the default values
    external_ip: ""
    local_ip: ""
    # Proxy IP used by Nginx or other loadbalancer
    k8s_proxy_ip: ""
  authentication:
    enable: false
    type: ""
    user: ""
    password: ""
  blockchain:
    ledger_conn: 127.0.0.1:32048
    sync_time: 30 seconds
    source: master
    destination: file
  database:
    type: sqlite
    ip: ""
    port: ""
    user: ""
    password: ""
    # whether to have system_query database to run against memory directly
    memory: true
  operator:
    # set member ID for operator - should only be used when readding operator to blockchain but keep (file) configs consistent
    member: ""
    cluster_name: new-cluster
    create_table: true
    update_tsd: true
    archive: true
    distributor: true
    db_name: tests
    partition:
        enable: false
        table: "*"
        column: timestamp
        interval: 14 days
        keep: 6
        sync: 1 day
  publisher:
    compress: true
    move: true
    db_location: file_name[0]
    table_location: file_name[1]
  mqtt:
    enable: false
    broker: driver.cloudmqtt.com
    port: 18785
    user: ibglowct
    password: MSY4e009J7ts
    log: false
    topic:
      name: anylogedgex
      db_name: test
      table: plc_device
      timestamp: now
      value_type: float
      value: bring [readings][][value]
  settings:
    # whether to deploy a local script that extends the default startup script
    deploy_local_script: "false"
    # An optional parameter for the number of workers threads that process requests which are send to the provided IP and Port.
    tcp_thread_pool: 6
    # Amount of time (in seconds) until REST timeout
    rest_timeout: 30
    # The number of concurrent threads supporting HTTP requests.
    rest_threads: 5
    # Sets the number of threads supporting queries (the default is 3).
    query_pool: 3
    write_immediate: true
    threshold_time : 60 seconds
    threshold_volume: 10KB



