version: "2.2"
services:
  anylog-operator-node2:
    image: anylogco/anylog-network:develop
    env_file:
      - anylog_configs.env
    container_name: anylog-operator-node2
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - anylog-operator-node2-anylog:/app/AnyLog-Network/anylog
      - anylog-operator-node2-blockchain:/app/AnyLog-Network/blockchain
      - anylog-operator-node2-data:/app/AnyLog-Network/data
      - anylog-operator-node2-local-scripts:/app/AnyLog-Network/scripts
volumes:
  anylog-operator-node2-anylog:
  anylog-operator-node2-blockchain:
  anylog-operator-node2-data:
  anylog-operator-node2-local-scripts:
