version: "2.2"
services:
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    network_mode: "host"w
    environment:
      - CONN_IP=${CONN_IP}
      - CLI_PORT=${CLI_PORT}
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  remote-cli:
  remote-cli-current:
